# Generated by Django 5.1.1 on 2024-10-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField()),
                ('ename', models.CharField(max_length=50)),
                ('esalary', models.IntegerField()),
                ('eaddress', models.CharField(max_length=50)),
                ('econtact', models.BigIntegerField()),
            ],
        ),
    ]
